version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      container_name: backend
  environment:
    - DATABASE_HOST=alleydb
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=mysecretpass
  ports:
    - 8080:8080
  depends_on:
    - db

  db:
    container_name: alleydb
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpass
    ports:
      - 5431:5431
    volumes:
      - postgresdb:/var/lib/postgresql/data

volumes:
  postgresdb:
